global_overrides:
#   - "fft_size = 1024;"
#   - "tau = 600;"

listen_port_base: 6100

mumble:
  remote_host: mumble-server.example.com
  remote_port: 3500
  default_channel: Radio Channels

devices:
  - id: rtlsdr_34
    type: rtlsdr_airband.rtlsdr
    serial: "00000034"
    gain: 28
    center_freq: 119.365

channels:
  - id: cyvr-tower-south
    freq: 118.700
    label: Vancouver Tower (South)
    designator: 6K00A3E

  - id: cyvr-tower-north
    freq: 119.550
    label: Vancouver Tower (North)
    designator: 6K00A3E

  - id: cyyj-tower-outer
    freq: 119.100
    label: Victoria (CYYJ) Tower (Outer)
    designator: 6K00A3E
