DEFAULT_CONFIG_FILE: str = "config.yaml"
DEFAULT_UDP_LISTEN_ADDR: str = "127.0.0.1"
DEFAULT_UDP_PORT_BASE: int = 6000
DEFAULT_PTT_TIMEOUT_SECS: float = 0.120  # 120 mS

DEFAULT_MINIMUM_VOICE_ACTIVE_SECS: float = 0.3
